--return {
--{
--    "SirVer/ultisnips",
--    dependencies = {
--      { "honza/vim-snippets" },
--      --{ "cristobaltapia/MySnippets" },
--    },
--    config = function()
--      vim.g.UltiSnipsSnippetDirectories = {
--        "UltiSnips",
--        vim.env.HOME .. ".local/share/nvim/lazy/MySnippets/Ultisnips",
--        vim.env.HOME .. ".local/share/nvim/lazy/vim-snippets/UltiSnips",
--      }
--
--      -- Set the smart function definition to use numpy style for docstrings
--      vim.g.ultisnips_python_style = "numpy"
--      vim.g.UltisnipsUsePythonVersion = 3
--      vim.g.UltiSnipsJumpForwardTrigger = "<c-j>"
--      vim.g.UltiSnipsJumpBackwardTrigger = "<c-z>"
--      vim.g.UltiSnipsExpandTrigger = "<c-k>"
--      vim.g.UltiSnipsListSnippets = "<c-.>"
--    end,
--  },
--}
